version: "3"
services:
    postgres:
        image: postgres
        environment:
          - POSTGRES_USER
          - POSTGRES_PASSWORD
          - POSTGRES_DB
        ports:
          - '5432:5432'
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql