version: "3"
services:
    postgres:
        image: postgres
        environment:
          - POSTGRES_USER
          - POSTGRES_PASSWORD
          - POSTGRES_DB
        ports:
          - '5432:5432'
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          timeout: 5s
          retries: 5
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
    app:
      build: .
      environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_HOST
        - MODE
        - PORT
      ports:
        - "8000:8000"
      links:
        - postgres
      depends_on:
        postgres:
          condition: service_healthy