name: Backend API Rest factory linter

on:
  push:
  pull_request:
  release:

jobs:
  lint:
    name: ESLint Linter
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: .

    steps:
      - name: Retrieving Latest Code
        uses: actions/checkout@v2

      - name: Installing NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Installing Project Dependencies
        run: npm install

      - name: Executing Linter Scan
        run: npm run lint
