name: Publish

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Retrieving Latest Code
        uses: actions/checkout@v2

      - name: Installing NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Installing Project Dependencies
        run: npm install
      - name: Build typescript
        run: npm run build
      - name: Publish code
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
